[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "uvicorn api:app --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100 